apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-got-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-got-router
  template:
    metadata:
      labels:
        app: camel-got-router
    spec:
      containers:
        - name: camel-got-router
          image: localhost/ms-apache-camel-training:latest
          imagePullPolicy: Never
          env:
            - name: APP_ROUTE_EXERCISE1_ENABLED
              value: "false"
            - name: APP_ROUTE_EXERCISE2_ENABLED
              value: "false"
            - name: APP_ROUTE_EXERCISE3_ENABLED
              value: "false"
            - name: APP_ROUTE_EXERCISE4_ENABLED
              value: "false"
            - name: APP_ROUTE_EXERCISE5_ENABLED
              value: "false"
            - name: APP_ROUTE_TRAINING_ENABLED
              value: "false"
            - name: APP_ROUTE_GAMEOFTHRONES_ENABLED
              value: "true"
            - name: RABBITMQ_HOST
              value: "rabbitmq.default.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
